### ISSUE TITLE
Disable gem deletion.

### ISSUE THREAD

**Issue by InflamedSebi** [Fairy-/PvPToggle#4]
Detect and disable deleting of gems via players Trash can.
If this is not cancelable, just detect it and give that player a new gem.

Also add a permission to bypass the deletion tracker.

**Comment by Fairy-** [comment]
If player puts a item in the trashcan and is it is a gem, delete it and put it in the cursor slot.

**Comment by InflamedSebi** [comment]
oh and despawning of gems should make an announcement and teleport it to spawn?

**Comment by Fairy-** [comment]
spawn = gem lock?

**Comment by InflamedSebi** [comment]
Trash is 179, 197 is in the code ... thats why it is not spawning a new gem on trashing.
